# Generated by Django 5.2.8 on 2026-05-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cinema',
            field=models.CharField(default='Одеса, ТРЦ Gagarinn Plaza', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='hall',
            field=models.CharField(default='3', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
