# Generated by Django 5.2.8 on 2026-05-24 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_booking_cinema_booking_hall_booking_selected_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('cinema', models.CharField(max_length=150)),
                ('hall', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seat_code', models.CharField(max_length=10)),
                ('seat_type', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_records', to='main.booking')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('movie', 'cinema', 'hall', 'date', 'time', 'seat_code'), name='unique_booked_seat_per_session')],
            },
        ),
    ]
